data:
  dataset: "kitti"
  train_path: "/Users/nabeelnazeer/Documents/Project-s6/Datasets/data_scene_flow/training"
  img_height: 256
  img_width: 832
  max_samples: null  # Remove sample limit to use full dataset

training:
  batch_size: 8     # Increased for full dataset
  num_epochs: 30    # Adjusted for full dataset
  learning_rate: 0.0001
  weight_decay: 0.0001
  scheduler_step_size: 10
  scheduler_gamma: 0.1

model:
  name: "resnet_depth"
  pretrained: true

logging:
  use_wandb: false  # Add this line to disable wandb
  save_dir: "checkpoints"
  log_interval: 50
