data:
  dataset: "kitti"
  base_path: "C:/Users/jesli/Downloads/data_scene_flow"
  train_path: "C:/Users/jesli/Downloads/data_scene_flow/training"
  test_path: "C:/Users/jesli/Downloads/data_scene_flow/testing"
  img_height: 256
  img_width: 832
  max_samples: null  # Ensure this is null to use full dataset

training:
  batch_size: 4          # Reduced for stability
  num_epochs: 40
  learning_rate: 0.0002  # Slightly increased
  weight_decay: 0.0001
  scheduler_step_size: 5  # More frequent adjustments
  scheduler_gamma: 0.7    # Less aggressive decay
  num_workers: 4    # Optimal for most GPUs
  pin_memory: true  # Important for GPU training
  cuda: true       # Force CUDA usage
  min_depth: 0.001          # Minimum valid depth
  max_depth: 80.0           # Maximum valid depth
  grad_clip: 1.0            # Add gradient clipping
  epsilon: 1e-7

model:
  name: "resnet_depth"
  pretrained: true
  depth_scale: 80.0         # Maximum depth range
  min_depth: 0.001         # Minimum depth range

logging:
  use_wandb: false  # Add this line to disable wandb
  save_dir: "checkpoints"
  log_interval: 50
